server:
  port: 8181

spring:
  application:
    name: SERVICE-TEST
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth_db?createIfNotExists=true
    username: root
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
